// <auto-generated />
using ELearning.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELearning.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ELearning.Api.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Poznaj podstawy i zaawansowane techniki SQL...",
                            ImageSrc = "/src/course/placeholder_sql.png",
                            Instructor = "Michał Nowak",
                            Rating = 5.0,
                            Title = "Kurs Nauki SQL"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Zacznij swoją przygodę z programowaniem w Pythonie...",
                            ImageSrc = "/src/course/placeholder_python.png",
                            Instructor = "Jan Kowalski",
                            Rating = 4.5,
                            Title = "Kurs Pythona"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Wprowadzenie do świata Sztucznej Inteligencji...",
                            ImageSrc = "/src/course/placeholder_ai.png",
                            Instructor = "Michał Nowak",
                            Rating = 4.0,
                            Title = "Kurs AI"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Buduj nowoczesne, wieloplatformowe aplikacje z .NET Core...",
                            ImageSrc = "/src/course/placeholder_dotnet.png",
                            Instructor = "Michał Nowak",
                            Rating = 5.0,
                            Title = "Kurs .Net Core"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
